// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_01_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_02_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_03_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_04_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_05_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_06_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_07_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_08_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_09_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_10_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_11_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_12_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_13_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_14_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_15_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_16_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_17_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_18_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_19_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_31_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_32_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_34_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_41_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_42_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_44_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_45_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_51_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_52_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_53_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_54_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_61_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_63_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_64_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_65_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_66_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_67_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_68_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_01_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_02_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_03_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_04_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_05_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_06_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_07_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_08_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_09_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_10_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_11_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_12_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_13_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_14_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_15_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_16_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_17_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_18_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_19_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_31_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_32_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_34_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_41_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_42_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_44_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_45_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_51_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_52_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_53_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_54_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_61_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_63_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_64_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_65_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_66_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_67_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_68_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_01_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_02_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_03_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_04_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_05_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_06_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_07_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_08_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_09_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_10_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_11_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_12_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_13_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_14_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_15_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_16_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_17_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_18_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_19_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_31_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_32_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_34_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_41_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_42_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_44_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_45_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_51_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_52_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_53_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_54_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_61_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_63_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_64_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_65_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_66_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_67_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_68_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_01_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_02_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_03_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_04_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_05_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_06_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_07_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_08_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_09_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_10_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_11_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_12_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_13_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_14_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_15_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_16_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_17_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_18_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_19_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_31_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_32_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_34_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_41_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_42_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_44_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_45_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_51_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_52_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_53_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_54_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_61_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_63_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_64_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_65_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_66_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_67_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_68_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_01_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_02_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_03_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_04_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_05_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_06_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_07_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_08_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_09_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_10_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_11_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_12_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_13_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_14_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_15_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_16_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_17_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_18_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_19_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_31_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_32_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_34_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_41_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_42_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_44_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_45_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_51_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_52_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_53_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_54_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_61_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_63_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_64_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_65_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_66_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_67_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_68_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_01_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_02_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_03_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_04_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_05_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_06_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_07_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_08_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_09_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_10_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_11_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_12_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_13_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_14_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_15_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_16_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_17_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_18_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_19_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_31_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_32_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_34_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_41_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_42_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_44_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_45_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_51_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_52_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_53_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_54_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_61_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_63_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_64_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_65_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_66_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_67_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_68_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_01_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_02_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_03_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_04_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_05_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_06_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_07_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_08_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_09_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_10_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_11_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_12_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_13_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_14_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_15_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_16_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_17_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_18_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_19_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_31_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_32_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_34_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_41_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_42_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_44_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_45_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_51_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_52_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_53_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_54_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_61_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_63_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_64_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_65_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_66_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_67_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_68_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_01_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_02_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_03_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_04_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_05_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_06_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_07_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_08_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_09_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_10_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_11_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_12_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_13_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_14_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_15_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_16_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_17_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_18_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_19_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_31_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_32_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_34_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_41_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_42_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_44_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_45_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_51_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_52_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_53_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_54_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_61_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_63_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_64_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_65_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_66_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_67_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_68_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_01_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_02_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_03_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_04_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_05_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_06_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_07_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_08_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_09_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_10_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_11_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_12_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_13_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_14_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_15_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_16_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_17_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_18_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_19_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_31_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_32_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_34_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_41_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_42_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_44_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_45_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_51_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_52_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_53_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_54_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_61_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_63_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_64_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_65_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_66_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_67_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_68_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_01_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_02_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_03_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_04_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_05_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_06_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_07_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_08_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_09_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_10_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_11_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_12_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_13_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_14_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_15_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_16_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_17_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_18_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_19_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_31_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_32_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_34_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_41_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_42_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_44_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_45_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_51_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_52_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_53_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_54_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_61_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_63_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_64_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_65_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_66_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_67_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_68_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_01_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_02_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_03_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_04_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_05_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_06_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_07_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_08_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_09_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_10_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_11_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_12_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_13_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_14_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_15_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_16_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_17_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_18_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_19_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_31_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_32_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_34_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_41_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_42_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_44_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_45_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_51_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_52_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_53_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_54_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_61_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_63_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_64_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_65_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_66_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_67_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_68_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_01_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_02_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_03_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_04_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_05_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_06_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_07_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_08_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_09_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_10_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_11_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_12_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_13_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_14_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_15_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_16_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_17_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_18_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_19_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_31_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_32_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_34_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_41_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_42_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_44_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_45_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_51_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_52_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_53_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_54_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_61_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_63_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_64_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_65_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_66_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_67_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_68_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_01_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_02_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_03_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_04_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_05_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_06_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_07_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_08_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_09_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_10_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_11_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_12_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_13_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_14_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_15_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_16_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_17_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_18_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_19_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_31_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_32_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_34_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_41_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_42_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_44_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_45_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_51_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_52_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_53_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_54_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_61_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_63_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_64_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_65_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_66_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_67_good();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_68_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_01_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_02_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_03_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_04_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_05_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_06_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_07_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_08_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_09_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_10_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_11_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_12_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_13_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_14_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_15_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_16_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_17_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_18_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_19_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_31_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_32_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_34_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_41_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_42_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_44_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_45_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_51_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_52_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_53_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_54_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_61_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_63_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_64_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_65_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_66_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_67_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_cpy_68_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_01_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_02_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_03_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_04_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_05_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_06_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_07_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_08_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_09_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_10_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_11_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_12_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_13_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_14_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_15_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_16_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_17_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_18_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_19_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_31_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_32_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_34_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_41_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_42_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_44_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_45_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_51_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_52_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_53_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_54_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_61_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_63_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_64_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_65_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_66_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_67_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_loop_68_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_01_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_02_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_03_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_04_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_05_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_06_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_07_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_08_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_09_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_10_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_11_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_12_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_13_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_14_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_15_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_16_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_17_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_18_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_19_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_31_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_32_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_34_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_41_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_42_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_44_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_45_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_51_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_52_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_53_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_54_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_61_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_63_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_64_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_65_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_66_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_67_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memcpy_68_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_01_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_02_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_03_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_04_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_05_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_06_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_07_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_08_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_09_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_10_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_11_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_12_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_13_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_14_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_15_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_16_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_17_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_18_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_19_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_31_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_32_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_34_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_41_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_42_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_44_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_45_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_51_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_52_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_53_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_54_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_61_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_63_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_64_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_65_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_66_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_67_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_memmove_68_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_01_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_02_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_03_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_04_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_05_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_06_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_07_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_08_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_09_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_10_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_11_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_12_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_13_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_14_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_15_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_16_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_17_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_18_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_19_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_31_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_32_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_34_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_41_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_42_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_44_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_45_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_51_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_52_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_53_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_54_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_61_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_63_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_64_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_65_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_66_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_67_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__char_ncpy_68_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_01_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_02_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_03_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_04_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_05_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_06_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_07_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_08_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_09_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_10_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_11_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_12_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_13_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_14_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_15_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_16_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_17_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_18_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_19_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_31_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_32_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_34_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_41_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_42_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_44_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_45_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_51_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_52_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_53_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_54_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_61_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_63_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_64_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_65_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_66_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_67_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__loop_68_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_01_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_02_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_03_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_04_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_05_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_06_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_07_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_08_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_09_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_10_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_11_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_12_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_13_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_14_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_15_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_16_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_17_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_18_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_19_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_31_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_32_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_34_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_41_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_42_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_44_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_45_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_51_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_52_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_53_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_54_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_61_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_63_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_64_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_65_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_66_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_67_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memcpy_68_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_01_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_02_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_03_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_04_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_05_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_06_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_07_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_08_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_09_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_10_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_11_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_12_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_13_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_14_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_15_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_16_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_17_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_18_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_19_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_31_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_32_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_34_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_41_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_42_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_44_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_45_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_51_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_52_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_53_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_54_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_61_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_63_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_64_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_65_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_66_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_67_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__memmove_68_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_01_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_02_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_03_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_04_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_05_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_06_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_07_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_08_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_09_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_10_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_11_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_12_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_13_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_14_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_15_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_16_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_17_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_18_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_19_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_31_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_32_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_34_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_41_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_42_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_44_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_45_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_51_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_52_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_53_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_54_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_61_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_63_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_64_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_65_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_66_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_67_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_cpy_68_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_01_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_02_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_03_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_04_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_05_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_06_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_07_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_08_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_09_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_10_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_11_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_12_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_13_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_14_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_15_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_16_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_17_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_18_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_19_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_31_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_32_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_34_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_41_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_42_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_44_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_45_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_51_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_52_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_53_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_54_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_61_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_63_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_64_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_65_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_66_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_67_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_loop_68_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_01_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_02_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_03_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_04_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_05_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_06_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_07_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_08_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_09_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_10_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_11_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_12_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_13_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_14_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_15_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_16_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_17_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_18_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_19_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_31_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_32_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_34_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_41_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_42_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_44_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_45_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_51_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_52_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_53_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_54_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_61_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_63_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_64_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_65_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_66_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_67_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memcpy_68_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_01_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_02_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_03_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_04_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_05_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_06_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_07_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_08_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_09_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_10_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_11_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_12_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_13_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_14_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_15_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_16_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_17_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_18_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_19_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_31_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_32_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_34_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_41_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_42_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_44_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_45_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_51_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_52_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_53_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_54_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_61_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_63_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_64_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_65_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_66_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_67_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_memmove_68_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_01_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_02_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_03_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_04_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_05_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_06_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_07_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_08_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_09_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_10_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_11_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_12_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_13_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_14_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_15_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_16_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_17_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_18_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_19_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_31_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_32_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_34_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_41_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_42_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_44_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_45_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_51_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_52_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_53_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_54_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_61_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_63_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_64_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_65_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_66_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_67_bad();

	void CWE131_Incorrect_Calculation_Of_Buffer_Size__wchar_t_ncpy_68_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
