// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_01_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_02_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_03_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_04_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_05_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_06_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_07_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_08_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_09_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_10_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_11_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_12_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_13_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_14_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_15_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_16_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_17_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_18_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_19_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_01_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_02_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_03_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_04_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_05_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_06_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_07_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_08_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_09_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_10_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_11_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_12_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_13_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_14_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_15_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_16_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_17_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_18_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_19_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_01_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_02_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_03_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_04_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_05_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_06_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_07_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_08_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_09_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_10_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_11_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_12_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_13_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_14_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_15_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_16_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_17_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_18_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_19_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_01_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_02_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_03_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_04_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_05_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_06_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_07_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_08_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_09_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_10_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_11_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_12_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_13_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_14_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_15_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_16_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_17_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_18_good();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_19_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_01_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_02_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_03_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_04_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_05_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_06_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_07_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_08_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_09_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_10_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_11_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_12_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_13_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_14_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_15_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_16_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_17_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_18_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32alloca_19_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_01_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_02_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_03_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_04_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_05_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_06_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_07_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_08_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_09_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_10_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_11_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_12_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_13_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_14_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_15_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_16_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_17_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_18_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__char_w32declare_19_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_01_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_02_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_03_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_04_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_05_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_06_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_07_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_08_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_09_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_10_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_11_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_12_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_13_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_14_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_15_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_16_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_17_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_18_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32alloca_19_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_01_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_02_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_03_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_04_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_05_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_06_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_07_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_08_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_09_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_10_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_11_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_12_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_13_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_14_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_15_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_16_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_17_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_18_bad();

	void CWE226_Sensitive_Information_Uncleared_Before_Release__wchar_t_w32declare_19_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
