/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	global_argc = argc;
	global_argv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_01_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_01_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_02_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_02_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_03_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_03_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_04_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_04_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_05_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_05_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_06_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_06_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_07_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_07_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_08_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_08_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_09_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_09_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_10_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_10_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_11_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_11_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_12_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_12_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_13_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_13_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_14_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_14_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_15_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_15_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_16_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_16_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_17_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_17_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_18_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_18_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_19_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_19_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_01_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_01_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_02_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_02_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_03_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_03_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_04_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_04_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_05_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_05_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_06_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_06_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_07_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_07_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_08_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_08_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_09_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_09_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_10_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_10_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_11_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_11_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_12_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_12_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_13_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_13_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_14_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_14_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_15_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_15_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_16_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_16_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_17_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_17_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_18_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_18_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_19_good();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_19_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_01_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_01_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_02_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_02_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_03_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_03_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_04_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_04_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_05_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_05_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_06_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_06_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_07_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_07_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_08_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_08_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_09_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_09_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_10_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_10_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_11_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_11_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_12_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_12_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_13_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_13_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_14_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_14_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_15_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_15_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_16_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_16_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_17_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_17_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_18_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_18_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_19_good();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_19_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_01_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_01_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_02_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_02_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_03_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_03_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_04_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_04_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_05_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_05_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_06_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_06_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_07_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_07_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_08_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_08_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_09_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_09_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_10_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_10_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_11_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_11_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_12_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_12_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_13_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_13_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_14_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_14_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_15_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_15_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_16_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_16_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_17_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_17_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_18_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_18_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_19_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_19_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_01_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_01_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_02_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_02_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_03_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_03_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_04_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_04_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_05_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_05_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_06_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_06_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_07_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_07_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_08_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_08_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_09_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_09_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_10_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_10_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_11_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_11_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_12_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_12_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_13_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_13_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_14_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_14_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_15_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_15_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_16_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_16_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_17_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_17_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_18_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_18_good();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_19_good();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_19_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_01_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_01_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_02_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_02_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_03_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_03_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_04_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_04_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_05_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_05_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_06_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_06_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_07_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_07_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_08_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_08_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_09_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_09_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_10_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_10_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_11_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_11_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_12_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_12_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_13_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_13_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_14_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_14_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_15_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_15_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_16_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_16_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_17_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_17_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_18_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_18_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_19_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_19_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_01_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_01_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_02_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_02_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_03_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_03_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_04_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_04_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_05_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_05_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_06_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_06_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_07_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_07_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_08_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_08_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_09_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_09_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_10_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_10_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_11_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_11_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_12_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_12_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_13_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_13_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_14_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_14_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_15_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_15_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_16_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_16_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_17_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_17_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_18_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_18_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_19_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_19_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_01_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_01_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_02_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_02_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_03_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_03_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_04_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_04_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_05_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_05_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_06_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_06_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_07_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_07_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_08_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_08_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_09_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_09_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_10_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_10_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_11_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_11_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_12_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_12_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_13_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_13_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_14_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_14_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_15_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_15_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_16_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_16_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_17_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_17_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_18_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_18_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_19_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_19_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_01_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_01_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_02_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_02_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_03_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_03_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_04_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_04_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_05_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_05_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_06_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_06_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_07_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_07_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_08_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_08_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_09_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_09_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_10_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_10_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_11_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_11_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_12_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_12_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_13_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_13_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_14_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_14_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_15_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_15_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_16_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_16_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_17_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_17_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_18_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_18_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_19_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_19_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_01_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_01_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_02_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_02_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_03_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_03_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_04_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_04_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_05_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_05_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_06_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_06_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_07_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_07_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_08_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_08_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_09_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_09_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_10_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_10_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_11_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_11_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_12_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_12_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_13_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_13_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_14_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_14_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_15_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_15_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_16_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_16_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_17_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_17_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_18_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_18_good();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_19_good();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_19_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */





#ifdef __cplusplus
	/* Calling C++ good functions */
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

#endif /* __cplusplus */

#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_01_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_01_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_02_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_02_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_03_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_03_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_04_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_04_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_05_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_05_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_06_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_06_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_07_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_07_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_08_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_08_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_09_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_09_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_10_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_10_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_11_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_11_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_12_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_12_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_13_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_13_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_14_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_14_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_15_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_15_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_16_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_16_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_17_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_17_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_18_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_18_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_19_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKeyEx_19_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_01_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_01_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_02_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_02_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_03_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_03_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_04_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_04_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_05_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_05_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_06_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_06_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_07_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_07_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_08_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_08_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_09_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_09_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_10_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_10_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_11_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_11_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_12_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_12_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_13_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_13_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_14_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_14_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_15_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_15_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_16_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_16_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_17_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_17_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_18_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_18_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegCreateKey_19_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegCreateKey_19_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_01_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_01_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_02_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_02_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_03_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_03_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_04_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_04_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_05_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_05_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_06_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_06_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_07_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_07_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_08_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_08_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_09_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_09_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_10_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_10_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_11_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_11_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_12_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_12_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_13_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_13_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_14_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_14_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_15_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_15_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_16_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_16_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_17_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_17_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_18_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_18_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_19_bad();");
	CWE272_Least_Privilege_Principal__char_w32RegOpenKeyEx_19_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_01_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_01_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_02_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_02_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_03_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_03_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_04_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_04_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_05_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_05_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_06_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_06_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_07_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_07_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_08_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_08_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_09_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_09_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_10_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_10_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_11_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_11_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_12_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_12_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_13_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_13_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_14_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_14_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_15_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_15_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_16_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_16_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_17_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_17_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_18_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_18_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_19_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegCreateUSKey_19_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_01_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_01_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_02_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_02_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_03_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_03_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_04_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_04_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_05_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_05_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_06_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_06_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_07_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_07_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_08_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_08_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_09_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_09_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_10_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_10_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_11_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_11_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_12_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_12_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_13_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_13_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_14_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_14_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_15_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_15_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_16_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_16_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_17_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_17_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_18_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_18_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_19_bad();");
	CWE272_Least_Privilege_Principal__char_w32SHRegOpenUSKey_19_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_01_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_01_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_02_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_02_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_03_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_03_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_04_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_04_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_05_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_05_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_06_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_06_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_07_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_07_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_08_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_08_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_09_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_09_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_10_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_10_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_11_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_11_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_12_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_12_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_13_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_13_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_14_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_14_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_15_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_15_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_16_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_16_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_17_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_17_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_18_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_18_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_19_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKeyEx_19_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_01_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_01_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_02_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_02_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_03_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_03_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_04_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_04_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_05_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_05_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_06_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_06_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_07_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_07_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_08_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_08_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_09_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_09_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_10_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_10_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_11_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_11_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_12_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_12_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_13_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_13_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_14_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_14_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_15_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_15_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_16_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_16_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_17_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_17_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_18_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_18_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_19_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegCreateKey_19_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_01_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_01_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_02_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_02_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_03_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_03_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_04_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_04_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_05_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_05_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_06_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_06_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_07_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_07_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_08_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_08_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_09_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_09_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_10_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_10_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_11_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_11_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_12_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_12_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_13_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_13_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_14_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_14_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_15_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_15_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_16_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_16_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_17_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_17_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_18_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_18_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_19_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32RegOpenKeyEx_19_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_01_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_01_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_02_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_02_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_03_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_03_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_04_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_04_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_05_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_05_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_06_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_06_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_07_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_07_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_08_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_08_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_09_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_09_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_10_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_10_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_11_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_11_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_12_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_12_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_13_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_13_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_14_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_14_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_15_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_15_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_16_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_16_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_17_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_17_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_18_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_18_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_19_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegCreateUSKey_19_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_01_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_01_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_02_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_02_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_03_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_03_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_04_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_04_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_05_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_05_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_06_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_06_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_07_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_07_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_08_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_08_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_09_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_09_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_10_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_10_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_11_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_11_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_12_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_12_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_13_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_13_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_14_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_14_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_15_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_15_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_16_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_16_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_17_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_17_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_18_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_18_bad();

	printLine("Calling CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_19_bad();");
	CWE272_Least_Privilege_Principal__wchar_t_w32SHRegOpenUSKey_19_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-CALLS */




	
#ifdef __cplusplus
	/* Calling C++ bad functions */
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */
	
#endif /* __cplusplus */

#endif /* OMITBAD */

	return 0;

} 
