/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	global_argc = argc;
	global_argv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_01_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_01_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_02_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_02_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_03_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_03_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_04_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_04_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_05_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_05_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_06_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_06_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_07_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_07_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_08_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_08_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_09_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_09_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_10_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_10_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_11_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_11_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_12_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_12_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_13_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_13_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_14_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_14_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_15_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_15_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_16_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_16_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_17_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_17_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_18_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_18_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_19_good();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_19_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_01_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_01_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_02_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_02_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_03_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_03_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_04_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_04_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_05_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_05_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_06_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_06_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_07_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_07_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_08_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_08_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_09_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_09_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_10_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_10_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_11_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_11_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_12_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_12_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_13_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_13_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_14_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_14_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_15_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_15_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_16_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_16_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_17_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_17_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_18_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_18_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_19_good();");
	CWE284_Access_Control_Issues__char_w32CreateFile_19_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_01_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_01_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_02_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_02_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_03_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_03_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_04_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_04_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_05_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_05_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_06_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_06_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_07_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_07_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_08_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_08_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_09_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_09_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_10_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_10_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_11_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_11_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_12_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_12_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_13_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_13_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_14_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_14_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_15_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_15_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_16_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_16_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_17_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_17_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_18_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_18_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_19_good();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_19_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_01_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_01_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_02_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_02_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_03_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_03_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_04_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_04_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_05_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_05_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_06_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_06_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_07_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_07_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_08_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_08_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_09_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_09_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_10_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_10_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_11_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_11_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_12_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_12_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_13_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_13_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_14_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_14_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_15_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_15_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_16_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_16_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_17_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_17_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_18_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_18_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_19_good();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_19_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_01_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_01_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_02_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_02_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_03_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_03_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_04_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_04_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_05_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_05_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_06_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_06_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_07_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_07_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_08_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_08_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_09_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_09_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_10_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_10_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_11_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_11_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_12_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_12_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_13_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_13_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_14_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_14_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_15_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_15_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_16_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_16_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_17_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_17_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_18_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_18_good();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_19_good();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_19_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_01_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_01_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_02_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_02_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_03_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_03_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_04_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_04_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_05_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_05_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_06_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_06_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_07_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_07_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_08_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_08_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_09_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_09_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_10_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_10_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_11_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_11_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_12_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_12_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_13_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_13_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_14_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_14_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_15_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_15_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_16_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_16_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_17_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_17_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_18_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_18_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_19_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_19_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_01_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_01_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_02_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_02_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_03_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_03_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_04_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_04_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_05_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_05_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_06_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_06_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_07_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_07_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_08_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_08_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_09_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_09_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_10_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_10_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_11_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_11_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_12_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_12_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_13_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_13_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_14_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_14_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_15_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_15_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_16_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_16_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_17_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_17_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_18_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_18_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_19_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_19_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_01_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_01_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_02_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_02_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_03_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_03_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_04_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_04_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_05_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_05_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_06_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_06_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_07_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_07_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_08_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_08_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_09_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_09_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_10_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_10_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_11_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_11_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_12_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_12_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_13_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_13_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_14_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_14_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_15_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_15_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_16_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_16_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_17_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_17_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_18_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_18_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_19_good();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_19_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_01_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_01_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_02_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_02_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_03_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_03_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_04_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_04_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_05_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_05_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_06_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_06_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_07_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_07_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_08_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_08_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_09_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_09_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_10_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_10_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_11_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_11_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_12_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_12_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_13_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_13_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_14_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_14_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_15_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_15_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_16_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_16_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_17_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_17_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_18_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_18_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_19_good();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_19_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_01_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_01_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_02_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_02_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_03_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_03_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_04_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_04_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_05_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_05_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_06_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_06_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_07_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_07_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_08_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_08_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_09_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_09_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_10_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_10_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_11_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_11_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_12_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_12_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_13_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_13_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_14_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_14_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_15_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_15_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_16_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_16_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_17_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_17_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_18_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_18_good();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_19_good();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_19_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */





#ifdef __cplusplus
	/* Calling C++ good functions */
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

#endif /* __cplusplus */

#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_01_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_01_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_02_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_02_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_03_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_03_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_04_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_04_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_05_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_05_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_06_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_06_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_07_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_07_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_08_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_08_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_09_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_09_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_10_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_10_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_11_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_11_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_12_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_12_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_13_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_13_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_14_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_14_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_15_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_15_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_16_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_16_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_17_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_17_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_18_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_18_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateDesktop_19_bad();");
	CWE284_Access_Control_Issues__char_w32CreateDesktop_19_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_01_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_01_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_02_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_02_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_03_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_03_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_04_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_04_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_05_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_05_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_06_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_06_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_07_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_07_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_08_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_08_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_09_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_09_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_10_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_10_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_11_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_11_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_12_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_12_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_13_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_13_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_14_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_14_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_15_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_15_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_16_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_16_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_17_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_17_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_18_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_18_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateFile_19_bad();");
	CWE284_Access_Control_Issues__char_w32CreateFile_19_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_01_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_01_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_02_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_02_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_03_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_03_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_04_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_04_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_05_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_05_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_06_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_06_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_07_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_07_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_08_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_08_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_09_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_09_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_10_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_10_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_11_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_11_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_12_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_12_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_13_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_13_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_14_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_14_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_15_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_15_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_16_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_16_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_17_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_17_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_18_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_18_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32CreateWindowStation_19_bad();");
	CWE284_Access_Control_Issues__char_w32CreateWindowStation_19_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_01_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_01_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_02_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_02_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_03_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_03_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_04_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_04_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_05_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_05_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_06_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_06_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_07_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_07_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_08_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_08_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_09_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_09_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_10_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_10_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_11_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_11_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_12_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_12_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_13_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_13_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_14_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_14_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_15_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_15_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_16_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_16_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_17_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_17_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_18_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_18_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_19_bad();");
	CWE284_Access_Control_Issues__char_w32RegCreateKeyEx_19_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_01_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_01_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_02_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_02_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_03_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_03_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_04_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_04_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_05_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_05_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_06_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_06_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_07_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_07_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_08_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_08_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_09_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_09_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_10_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_10_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_11_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_11_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_12_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_12_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_13_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_13_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_14_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_14_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_15_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_15_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_16_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_16_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_17_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_17_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_18_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_18_bad();

	printLine("Calling CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_19_bad();");
	CWE284_Access_Control_Issues__char_w32SHRegCreateUSKey_19_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_01_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_01_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_02_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_02_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_03_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_03_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_04_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_04_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_05_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_05_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_06_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_06_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_07_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_07_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_08_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_08_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_09_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_09_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_10_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_10_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_11_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_11_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_12_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_12_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_13_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_13_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_14_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_14_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_15_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_15_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_16_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_16_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_17_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_17_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_18_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_18_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_19_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateDesktop_19_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_01_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_01_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_02_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_02_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_03_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_03_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_04_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_04_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_05_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_05_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_06_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_06_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_07_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_07_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_08_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_08_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_09_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_09_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_10_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_10_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_11_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_11_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_12_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_12_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_13_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_13_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_14_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_14_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_15_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_15_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_16_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_16_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_17_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_17_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_18_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_18_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateFile_19_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateFile_19_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_01_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_01_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_02_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_02_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_03_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_03_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_04_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_04_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_05_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_05_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_06_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_06_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_07_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_07_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_08_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_08_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_09_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_09_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_10_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_10_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_11_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_11_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_12_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_12_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_13_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_13_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_14_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_14_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_15_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_15_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_16_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_16_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_17_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_17_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_18_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_18_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_19_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32CreateWindowStation_19_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_01_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_01_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_02_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_02_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_03_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_03_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_04_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_04_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_05_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_05_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_06_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_06_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_07_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_07_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_08_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_08_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_09_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_09_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_10_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_10_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_11_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_11_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_12_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_12_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_13_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_13_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_14_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_14_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_15_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_15_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_16_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_16_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_17_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_17_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_18_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_18_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_19_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32RegCreateKeyEx_19_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_01_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_01_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_02_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_02_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_03_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_03_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_04_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_04_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_05_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_05_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_06_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_06_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_07_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_07_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_08_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_08_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_09_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_09_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_10_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_10_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_11_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_11_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_12_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_12_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_13_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_13_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_14_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_14_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_15_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_15_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_16_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_16_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_17_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_17_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_18_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_18_bad();

	printLine("Calling CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_19_bad();");
	CWE284_Access_Control_Issues__wchar_t_w32SHRegCreateUSKey_19_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-CALLS */




	
#ifdef __cplusplus
	/* Calling C++ bad functions */
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */
	
#endif /* __cplusplus */

#endif /* OMITBAD */

	return 0;

} 
