// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_01_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_02_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_03_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_04_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_05_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_06_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_07_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_08_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_09_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_10_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_11_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_12_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_13_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_14_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_15_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_16_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_17_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_18_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_19_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_31_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_32_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_34_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_41_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_44_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_45_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_51_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_52_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_53_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_54_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_63_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_64_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_65_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_66_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_67_good();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_68_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_01_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_02_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_03_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_04_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_05_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_06_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_07_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_08_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_09_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_10_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_11_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_12_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_13_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_14_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_15_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_16_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_17_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_18_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_19_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_31_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_32_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_34_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_41_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_44_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_45_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_51_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_52_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_53_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_54_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_63_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_64_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_65_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_66_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_67_bad();

	void CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer__basic_68_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
