// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_01_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_02_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_03_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_04_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_05_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_06_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_07_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_08_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_09_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_10_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_11_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_12_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_13_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_14_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_15_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_16_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_17_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_18_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_19_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_31_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_32_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_34_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_41_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_42_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_44_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_45_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_51_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_52_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_53_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_54_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_61_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_63_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_64_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_65_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_66_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_67_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_68_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_01_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_02_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_03_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_04_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_05_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_06_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_07_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_08_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_09_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_10_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_11_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_12_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_13_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_14_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_15_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_16_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_17_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_18_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_19_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_31_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_32_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_34_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_41_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_42_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_44_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_45_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_51_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_52_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_53_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_54_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_61_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_63_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_64_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_65_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_66_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_67_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_68_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_01_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_02_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_03_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_04_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_05_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_06_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_07_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_08_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_09_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_10_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_11_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_12_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_13_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_14_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_15_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_16_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_17_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_18_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_19_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_31_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_32_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_34_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_41_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_42_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_44_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_45_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_51_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_52_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_53_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_54_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_61_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_63_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_64_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_65_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_66_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_67_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_68_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_01_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_02_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_03_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_04_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_05_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_06_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_07_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_08_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_09_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_10_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_11_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_12_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_13_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_14_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_15_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_16_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_17_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_18_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_19_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_31_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_32_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_34_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_41_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_42_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_44_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_45_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_51_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_52_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_53_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_54_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_61_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_63_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_64_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_65_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_66_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_67_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_68_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_01_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_02_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_03_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_04_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_05_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_06_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_07_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_08_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_09_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_10_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_11_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_12_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_13_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_14_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_15_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_16_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_17_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_18_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_19_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_31_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_32_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_34_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_41_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_42_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_44_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_45_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_51_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_52_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_53_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_54_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_61_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_63_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_64_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_65_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_66_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_67_good();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_68_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_01_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_02_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_03_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_04_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_05_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_06_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_07_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_08_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_09_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_10_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_11_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_12_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_13_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_14_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_15_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_16_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_17_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_18_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_19_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_31_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_32_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_34_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_41_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_42_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_44_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_45_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_51_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_52_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_53_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_54_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_61_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_63_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_64_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_65_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_66_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_67_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_68_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_01_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_02_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_03_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_04_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_05_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_06_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_07_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_08_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_09_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_10_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_11_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_12_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_13_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_14_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_15_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_16_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_17_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_18_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_19_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_31_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_32_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_34_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_41_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_42_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_44_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_45_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_51_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_52_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_53_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_54_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_61_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_63_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_64_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_65_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_66_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_67_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_68_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_01_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_02_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_03_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_04_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_05_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_06_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_07_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_08_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_09_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_10_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_11_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_12_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_13_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_14_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_15_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_16_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_17_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_18_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_19_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_31_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_32_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_34_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_41_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_42_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_44_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_45_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_51_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_52_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_53_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_54_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_61_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_63_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_64_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_65_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_66_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_67_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_68_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_01_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_02_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_03_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_04_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_05_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_06_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_07_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_08_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_09_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_10_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_11_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_12_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_13_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_14_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_15_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_16_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_17_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_18_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_19_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_31_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_32_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_34_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_41_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_42_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_44_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_45_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_51_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_52_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_53_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_54_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_61_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_63_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_64_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_65_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_66_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_67_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_68_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_01_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_02_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_03_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_04_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_05_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_06_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_07_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_08_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_09_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_10_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_11_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_12_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_13_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_14_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_15_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_16_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_17_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_18_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_19_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_31_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_32_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_34_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_41_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_42_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_44_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_45_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_51_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_52_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_53_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_54_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_61_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_63_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_64_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_65_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_66_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_67_good();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_68_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_01_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_02_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_03_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_04_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_05_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_06_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_07_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_08_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_09_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_10_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_11_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_12_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_13_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_14_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_15_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_16_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_17_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_18_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_19_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_31_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_32_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_34_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_41_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_42_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_44_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_45_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_51_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_52_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_53_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_54_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_61_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_63_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_64_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_65_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_66_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_67_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_connect_socket_68_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_01_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_02_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_03_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_04_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_05_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_06_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_07_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_08_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_09_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_10_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_11_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_12_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_13_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_14_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_15_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_16_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_17_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_18_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_19_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_31_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_32_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_34_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_41_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_42_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_44_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_45_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_51_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_52_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_53_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_54_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_61_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_63_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_64_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_65_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_66_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_67_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_Environment_68_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_01_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_02_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_03_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_04_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_05_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_06_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_07_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_08_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_09_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_10_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_11_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_12_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_13_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_14_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_15_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_16_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_17_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_18_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_19_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_31_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_32_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_34_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_41_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_42_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_44_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_45_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_51_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_52_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_53_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_54_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_61_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_63_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_64_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_65_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_66_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_67_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromConsole_68_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_01_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_02_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_03_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_04_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_05_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_06_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_07_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_08_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_09_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_10_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_11_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_12_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_13_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_14_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_15_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_16_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_17_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_18_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_19_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_31_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_32_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_34_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_41_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_42_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_44_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_45_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_51_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_52_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_53_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_54_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_61_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_63_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_64_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_65_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_66_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_67_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_fromFile_68_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_01_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_02_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_03_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_04_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_05_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_06_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_07_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_08_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_09_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_10_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_11_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_12_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_13_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_14_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_15_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_16_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_17_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_18_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_19_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_31_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_32_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_34_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_41_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_42_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_44_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_45_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_51_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_52_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_53_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_54_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_61_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_63_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_64_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_65_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_66_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_67_bad();

	void CWE427_Uncontrolled_Search_Path_Element__char_listen_socket_68_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_01_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_02_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_03_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_04_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_05_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_06_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_07_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_08_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_09_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_10_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_11_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_12_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_13_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_14_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_15_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_16_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_17_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_18_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_19_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_31_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_32_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_34_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_41_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_42_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_44_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_45_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_51_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_52_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_53_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_54_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_61_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_63_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_64_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_65_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_66_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_67_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_connect_socket_68_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_01_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_02_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_03_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_04_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_05_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_06_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_07_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_08_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_09_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_10_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_11_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_12_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_13_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_14_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_15_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_16_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_17_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_18_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_19_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_31_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_32_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_34_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_41_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_42_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_44_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_45_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_51_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_52_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_53_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_54_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_61_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_63_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_64_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_65_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_66_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_67_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_Environment_68_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_01_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_02_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_03_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_04_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_05_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_06_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_07_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_08_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_09_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_10_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_11_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_12_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_13_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_14_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_15_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_16_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_17_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_18_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_19_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_31_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_32_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_34_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_41_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_42_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_44_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_45_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_51_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_52_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_53_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_54_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_61_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_63_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_64_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_65_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_66_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_67_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromConsole_68_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_01_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_02_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_03_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_04_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_05_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_06_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_07_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_08_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_09_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_10_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_11_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_12_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_13_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_14_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_15_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_16_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_17_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_18_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_19_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_31_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_32_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_34_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_41_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_42_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_44_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_45_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_51_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_52_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_53_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_54_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_61_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_63_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_64_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_65_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_66_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_67_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_fromFile_68_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_01_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_02_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_03_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_04_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_05_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_06_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_07_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_08_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_09_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_10_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_11_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_12_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_13_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_14_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_15_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_16_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_17_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_18_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_19_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_31_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_32_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_34_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_41_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_42_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_44_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_45_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_51_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_52_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_53_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_54_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_61_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_63_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_64_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_65_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_66_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_67_bad();

	void CWE427_Uncontrolled_Search_Path_Element__wchar_t_listen_socket_68_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
