/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	global_argc = argc;
	global_argv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_01_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_01_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_02_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_02_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_03_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_03_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_04_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_04_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_05_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_05_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_06_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_06_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_07_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_07_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_08_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_08_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_09_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_09_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_10_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_10_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_11_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_11_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_12_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_12_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_13_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_13_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_14_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_14_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_15_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_15_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_16_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_16_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_17_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_17_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_18_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_18_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_19_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_19_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_01_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_01_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_02_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_02_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_03_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_03_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_04_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_04_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_05_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_05_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_06_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_06_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_07_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_07_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_08_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_08_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_09_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_09_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_10_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_10_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_11_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_11_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_12_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_12_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_13_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_13_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_14_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_14_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_15_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_15_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_16_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_16_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_17_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_17_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_18_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_18_good();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_19_good();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_19_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */





#ifdef __cplusplus
	/* Calling C++ good functions */
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

#endif /* __cplusplus */

#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_01_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_01_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_02_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_02_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_03_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_03_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_04_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_04_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_05_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_05_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_06_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_06_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_07_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_07_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_08_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_08_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_09_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_09_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_10_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_10_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_11_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_11_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_12_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_12_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_13_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_13_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_14_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_14_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_15_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_15_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_16_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_16_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_17_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_17_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_18_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_18_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_19_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__always_return_success_19_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_01_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_01_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_02_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_02_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_03_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_03_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_04_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_04_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_05_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_05_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_06_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_06_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_07_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_07_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_08_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_08_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_09_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_09_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_10_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_10_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_11_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_11_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_12_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_12_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_13_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_13_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_14_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_14_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_15_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_15_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_16_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_16_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_17_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_17_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_18_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_18_bad();

	printLine("Calling CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_19_bad();");
	CWE392_Failure_To_Report_Error_In_Status_Code__fail_to_set_error_code_19_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-CALLS */




	
#ifdef __cplusplus
	/* Calling C++ bad functions */
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */
	
#endif /* __cplusplus */

#endif /* OMITBAD */

	return 0;

} 
