/* NOTE - eventually this file will be automatically updated using a Perl script that understand
 * the naming of test case files, functions, and namespaces.
 */

#include <time.h>   /* for time() */
#include <stdlib.h> /* for srand() */

#include "std_testcase.h"
#include "testcases.h"

int main(int argc, char * argv[]) {

	/* seed randomness */

	srand( (unsigned)time(NULL) );

	global_argc = argc;
	global_argv = argv;

#ifndef OMITGOOD

	/* Calling C good functions */
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */
	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_01_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_01_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_02_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_02_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_03_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_03_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_04_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_04_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_05_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_05_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_06_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_06_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_07_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_07_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_08_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_08_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_09_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_09_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_10_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_10_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_11_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_11_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_12_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_12_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_13_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_13_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_14_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_14_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_15_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_15_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_16_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_16_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_17_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_17_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_18_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_18_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_19_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_19_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_31_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_31_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_32_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_32_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_34_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_34_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_41_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_41_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_42_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_42_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_44_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_44_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_45_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_45_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_51_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_51_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_52_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_52_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_53_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_53_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_54_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_54_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_61_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_61_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_63_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_63_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_64_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_64_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_65_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_65_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_66_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_66_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_67_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_67_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_68_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_68_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_01_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_01_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_02_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_02_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_03_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_03_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_04_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_04_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_05_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_05_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_06_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_06_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_07_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_07_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_08_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_08_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_09_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_09_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_10_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_10_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_11_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_11_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_12_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_12_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_13_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_13_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_14_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_14_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_15_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_15_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_16_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_16_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_17_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_17_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_18_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_18_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_19_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_19_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_31_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_31_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_32_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_32_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_34_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_34_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_41_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_41_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_42_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_42_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_44_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_44_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_45_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_45_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_51_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_51_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_52_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_52_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_53_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_53_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_54_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_54_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_61_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_61_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_63_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_63_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_64_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_64_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_65_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_65_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_66_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_66_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_67_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_67_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_68_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_68_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_01_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_01_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_02_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_02_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_03_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_03_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_04_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_04_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_05_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_05_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_06_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_06_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_07_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_07_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_08_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_08_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_09_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_09_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_10_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_10_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_11_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_11_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_12_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_12_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_13_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_13_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_14_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_14_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_15_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_15_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_16_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_16_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_17_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_17_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_18_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_18_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_19_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_19_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_31_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_31_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_32_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_32_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_34_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_34_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_41_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_41_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_42_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_42_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_44_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_44_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_45_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_45_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_51_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_51_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_52_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_52_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_53_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_53_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_54_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_54_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_61_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_61_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_63_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_63_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_64_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_64_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_65_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_65_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_66_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_66_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_67_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_67_good();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_68_good();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_68_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-CALLS */





#ifdef __cplusplus
	/* Calling C++ good functions */
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-CALLS */

#endif /* __cplusplus */

#endif /* OMITGOOD */

#ifndef OMITBAD

	/* Calling C bad functions */
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-CALLS */
	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_01_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_01_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_02_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_02_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_03_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_03_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_04_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_04_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_05_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_05_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_06_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_06_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_07_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_07_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_08_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_08_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_09_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_09_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_10_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_10_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_11_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_11_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_12_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_12_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_13_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_13_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_14_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_14_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_15_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_15_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_16_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_16_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_17_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_17_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_18_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_18_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_19_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_19_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_31_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_31_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_32_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_32_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_34_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_34_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_41_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_41_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_42_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_42_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_44_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_44_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_45_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_45_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_51_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_51_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_52_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_52_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_53_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_53_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_54_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_54_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_61_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_61_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_63_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_63_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_64_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_64_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_65_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_65_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_66_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_66_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_67_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_67_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__double_68_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__double_68_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_01_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_01_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_02_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_02_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_03_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_03_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_04_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_04_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_05_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_05_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_06_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_06_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_07_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_07_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_08_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_08_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_09_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_09_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_10_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_10_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_11_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_11_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_12_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_12_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_13_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_13_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_14_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_14_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_15_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_15_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_16_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_16_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_17_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_17_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_18_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_18_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_19_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_19_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_31_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_31_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_32_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_32_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_34_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_34_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_41_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_41_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_42_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_42_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_44_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_44_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_45_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_45_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_51_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_51_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_52_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_52_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_53_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_53_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_54_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_54_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_61_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_61_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_63_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_63_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_64_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_64_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_65_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_65_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_66_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_66_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_67_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_67_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__long_long_68_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__long_long_68_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_01_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_01_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_02_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_02_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_03_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_03_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_04_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_04_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_05_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_05_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_06_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_06_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_07_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_07_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_08_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_08_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_09_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_09_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_10_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_10_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_11_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_11_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_12_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_12_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_13_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_13_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_14_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_14_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_15_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_15_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_16_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_16_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_17_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_17_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_18_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_18_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_19_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_19_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_31_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_31_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_32_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_32_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_34_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_34_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_41_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_41_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_42_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_42_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_44_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_44_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_45_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_45_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_51_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_51_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_52_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_52_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_53_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_53_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_54_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_54_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_61_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_61_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_63_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_63_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_64_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_64_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_65_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_65_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_66_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_66_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_67_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_67_bad();

	printLine("Calling CWE467_Use_of_sizeof_on_Pointer_Type__struct_68_bad();");
	CWE467_Use_of_sizeof_on_Pointer_Type__struct_68_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-CALLS */




	
#ifdef __cplusplus
	/* Calling C++ bad functions */
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-CALLS */
	
#endif /* __cplusplus */

#endif /* OMITBAD */

	return 0;

} 
