// NOTE - eventually this file will be automatically updated using a Perl script that understand
// the naming of test case files, functions, and namespaces.

#ifndef _TESTCASES_H
#define _TESTCASES_H

#ifdef __cplusplus
extern "C" {
#endif

// declare C good and bad functions
#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
	void CWE467_Use_of_sizeof_on_Pointer_Type__double_01_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_02_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_03_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_04_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_05_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_06_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_07_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_08_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_09_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_10_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_11_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_12_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_13_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_14_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_15_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_16_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_17_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_18_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_19_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_31_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_32_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_34_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_41_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_42_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_44_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_45_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_51_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_52_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_53_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_54_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_61_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_63_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_64_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_65_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_66_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_67_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_68_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_01_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_02_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_03_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_04_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_05_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_06_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_07_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_08_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_09_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_10_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_11_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_12_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_13_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_14_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_15_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_16_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_17_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_18_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_19_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_31_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_32_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_34_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_41_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_42_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_44_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_45_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_51_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_52_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_53_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_54_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_61_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_63_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_64_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_65_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_66_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_67_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_68_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_01_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_02_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_03_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_04_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_05_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_06_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_07_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_08_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_09_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_10_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_11_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_12_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_13_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_14_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_15_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_16_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_17_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_18_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_19_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_31_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_32_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_34_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_41_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_42_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_44_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_45_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_51_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_52_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_53_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_54_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_61_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_63_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_64_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_65_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_66_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_67_good();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_68_good();

	/* END-AUTOGENERATED-C-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
	void CWE467_Use_of_sizeof_on_Pointer_Type__double_01_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_02_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_03_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_04_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_05_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_06_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_07_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_08_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_09_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_10_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_11_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_12_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_13_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_14_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_15_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_16_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_17_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_18_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_19_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_31_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_32_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_34_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_41_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_42_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_44_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_45_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_51_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_52_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_53_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_54_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_61_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_63_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_64_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_65_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_66_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_67_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__double_68_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_01_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_02_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_03_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_04_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_05_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_06_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_07_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_08_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_09_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_10_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_11_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_12_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_13_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_14_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_15_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_16_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_17_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_18_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_19_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_31_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_32_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_34_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_41_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_42_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_44_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_45_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_51_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_52_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_53_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_54_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_61_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_63_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_64_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_65_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_66_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_67_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__long_long_68_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_01_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_02_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_03_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_04_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_05_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_06_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_07_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_08_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_09_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_10_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_11_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_12_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_13_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_14_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_15_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_16_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_17_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_18_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_19_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_31_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_32_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_34_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_41_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_42_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_44_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_45_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_51_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_52_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_53_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_54_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_61_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_63_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_64_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_65_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_66_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_67_bad();

	void CWE467_Use_of_sizeof_on_Pointer_Type__struct_68_bad();

	/* END-AUTOGENERATED-C-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD

#ifdef __cplusplus
} // end extern "C"
#endif

#ifdef __cplusplus
// declare C++ namespaces and good and bad functions

#ifndef OMITGOOD
	/* BEGIN-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-GOOD-FUNCTION-DECLARATIONS */
#endif // OMITGOOD


#ifndef OMITBAD
	/* BEGIN-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */

	/* END-AUTOGENERATED-CPP-BAD-FUNCTION-DECLARATIONS */
#endif // OMITBAD


#endif // __cplusplus


#endif //  _TESTCASES_H
